In [ ]:
"Documents/D&D/Codes/merged_card_data.json"

In [3]:
a = None
while a:
    print("test")
print("done")

done


In [1]:

import random
import json
import numpy as np
import pygame
import os


pygame 2.3.0 (SDL 2.24.2, Python 3.10.10)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [5]:
from maputil import generate_minimap, Minimap #Function that generates three lists: nodes (descriptions of events at each location), map (similar to nodes, with a 1 if a node is present and 0 if absent), and connections (a list of arrays describing a sufficient and non-intersecting set of connections from each layer to the next)

In [6]:
minimap = Minimap(5,10)
print(len(minimap.nodes))
print(minimap.nodes)
print(minimap.map)

10
[[{'event': 1}, {'event': 3}, {'event': 3}, {'event': 5}, {'event': 2}], [{'event': 0}, {'event': 1}, {'event': 2}, {'event': 0}, {'event': 1}], [{'event': 1}, {'event': 5}, {'event': 4}, {'event': 4}, {'event': 5}], [{'event': 0}, {'event': 0}, {'event': 4}, {'event': 1}, {'event': 1}], [{'event': 0}, {'event': 2}, {'event': 0}, {'event': 4}, {'event': 3}], [{'event': 2}, {'event': 3}, {'event': 3}, {'event': 0}, {'event': 3}], [{'event': 4}, {'event': 5}, {'event': 3}, {'event': 5}, {'event': 0}], [{'event': 4}, {'event': 3}, {'event': 5}, {'event': 0}, {'event': 5}], [{'event': 3}, {'event': 1}, {'event': 4}, {'event': 2}, {'event': 2}], [{'event': 3}, {'event': 2}, {'event': 0}, {'event': 5}, {'event': 0}]]
[[1, 1, 1, 1, 1], [0, 1, 1, 0, 1], [1, 1, 1, 1, 1], [0, 0, 1, 1, 1], [0, 1, 0, 1, 1], [1, 1, 1, 0, 1], [1, 1, 1, 1, 0], [1, 1, 1, 0, 1], [1, 1, 1, 1, 1], [1, 1, 0, 1, 0]]


In [ ]:
cardtype = random.choice([0,1,2])
cardx = random.random() * screen_width
cardy = random.random() * screen_height
scene.append(card(setcodes[cardtype],cardnames[cardtype], cardx,cardy))

In [11]:
num_steps = 10
num_lanes = 5
special_steps = {0: 1, num_steps - 1: 1}
nodes, minimap, connections = generate_minimap(num_steps, num_lanes, special_steps)

In [14]:
nodes

[[{'event': 0}, {'event': 0}, {'event': 3}, {'event': 0}, {'event': 0}],
 [{'event': 0}, {'event': 1}, {'event': 5}, {'event': 4}, {'event': 0}],
 [{'event': 5}, {'event': 0}, {'event': 0}, {'event': 0}, {'event': 2}],
 [{'event': 3}, {'event': 0}, {'event': 4}, {'event': 1}, {'event': 0}],
 [{'event': 1}, {'event': 0}, {'event': 0}, {'event': 0}, {'event': 4}],
 [{'event': 0}, {'event': 4}, {'event': 0}, {'event': 2}, {'event': 0}],
 [{'event': 0}, {'event': 3}, {'event': 4}, {'event': 1}, {'event': 0}],
 [{'event': 3}, {'event': 4}, {'event': 2}, {'event': 5}, {'event': 0}],
 [{'event': 3}, {'event': 3}, {'event': 4}, {'event': 1}, {'event': 5}],
 [{'event': 0}, {'event': 0}, {'event': 2}, {'event': 0}, {'event': 0}]]

In [12]:
minimap

[[0, 0, 1, 0, 0],
 [0, 1, 1, 1, 0],
 [1, 0, 0, 0, 1],
 [1, 0, 1, 1, 0],
 [1, 0, 0, 0, 1],
 [0, 1, 0, 1, 0],
 [0, 1, 1, 1, 0],
 [1, 1, 1, 1, 0],
 [1, 1, 1, 1, 1],
 [0, 0, 1, 0, 0]]

In [13]:
connections

[array([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 1, 1, 1, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=uint8),
 array([[0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0]], dtype=uint8),
 array([[1, 0, 1, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0]], dtype=uint8),
 array([[1, 0, 0, 0, 1],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0]], dtype=uint8),
 None,
 array([[0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0]], dtype=uint8),
 array([[0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [1, 0, 0, 1, 0],
        [0, 0, 0, 0, 0]], dtype=uint8),
 array([[1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 1, 1],
        [0, 0, 0, 0, 0]], dtype=uint8),
 array([[0, 0

In [121]:

with open("merged_card_data.json", "r") as file:
    card_data = json.load(file)

def filter_cards(cards, sets, rarity, color):
    filtered_cards = [
        card_e for card_e in cards
        if card_e["set"] in sets
        and card_e["object"] != "card"
    ]
    return random.choice(filtered_cards) if filtered_cards else None
def split_type_line(type_line):
    if '—' in type_line:
        card_type, subtypes_str = type_line.split('—', 1)
        subtypes = subtypes_str.strip().split(' ')
        for subtype in subtypes:
            subtype = subtype.strip()
    else:
        card_type = type_line
        subtypes = []
    if "Legendary" in card_type:
        card_type = card_type[9:]
        legend = True
    else:
        legend = False
    card_type = card_type.strip().split(' ')
    for cardtype in card_type:
        cardtype = cardtype.strip()
    return card_type, subtypes, legend
shortened_card_data = []
for card in card_data:
    
    card_type, subtypes, legend = split_type_line(card["type_line"])
    shortened_card = {
        "set": [card["set"]],
        "rarity": [card["rarity"]],
        "color": card["color_identity"],
        "mana_cost": [i for i in card["mana_cost"] if i in "0123456789/WUBRGNPSXYZ"],
        "mana_symbols": [i for i in card["mana_cost"] if i in "WUBRGNPS"],
        "name": [card["name"]],
        "cmc": [card["cmc"]],
        "card_type": card_type,
        "subtypes": subtypes,
        "keywords": card["keywords"],
        "oracle_text": [card["oracle_text"]],
        "legend": [legend]
    }
    shortened_card_data.append(shortened_card)

# Save the shortened card data to a new JSON file
with open("shortened_card_data.json", "w") as file:
    json.dump(shortened_card_data, file)

In [31]:
target_sets = ["lrw", "mor"]
target_rarity = ["rare"]
target_color = [["G"]]

selected_card = filter_cards(card_data, target_sets, target_rarity, target_color)

if selected_card:
    print(f"Selected card: {selected_card['name']} from {selected_card['set']}")
else:
    print("No card found that matches the given criteria.")


No card found that matches the given criteria.


In [29]:
def match(card_e, params, exclusive, negparams=None, blankparams=None):
    all_params = set(params.keys())
    if negparams:
        all_params = all_params.union(set(negparams.keys()))
    if blankparams:
        all_params = all_params.union(set(blankparams.keys()))
    for param in all_params:
        if param in card_e:
            values = params.get(param, [])
            if isinstance(exclusive, dict):
                if (param in exclusive) and (param in params):
                    exclusive_param = exclusive[param]
                else:
                    exclusive_param = False#Default to inclusive mode
            else:
                exclusive_param = exclusive

            if negparams and (param in negparams) and (negparams[param]):
                if set(card_e[param]).intersection(set(negparams[param])):
                    return False

            if blankparams and (param in blankparams):
                if blankparams[param]:
                    if len(card_e[param]) == 0:
                        return False

            if len(card_e[param]) and len(values): #Blanks checked separately, therefore only check for overlap with values 
                if exclusive_param:
                    if not set(card_e[param]).issubset(set(values)):
                        return False
                else:
                    if not set(card_e[param]).intersection(set(values)):
                        return False

    return True



def select_cards(cards, n, params, exclusive=True, negparams=None, blankparams=None):
    matching_cards = [card_e for card_e in cards if match(card_e, params, exclusive, negparams, blankparams)]
    if len(matching_cards) < n:
        return random.sample(matching_cards, len(matching_cards))
    else:
        return random.sample(matching_cards, n)

with open("shortened_card_data.json", "r") as file:
    shortened_card_data = json.load(file)

fightparams = {"set": [],
        "rarity": ["common","uncommon","rare", "mythic rare"],
        "color": ["W", "U", "B", "R", "G"],
        "mana_cost": [],
        "mana_symbols": [],
        "name": [],
        "cmc": [],
        "card_type": [],
        "subtypes": [],
        "keywords": [],
        "oracle_text": [],
        "legend": []}#Values that are desired, such that at least one should be present if a card has any values for that parameter

exclusive_params = {"set": False,
        "rarity": False,
        "color": True,
        "mana_cost": False,
        "mana_symbols": False,
        "name": False,
        "cmc": False,
        "card_type": False,
        "subtypes": False,
        "keywords": False,
        "oracle_text": False,
        "legend": False}#Whether the parameter list is exclusive, ie any values outside of that list are disallowed if exclusive_params[params]==True
blankparams = {"set": False,
        "rarity": False,
        "color": False,
        "mana_cost": False,
        "mana_symbols": False,
        "name": False,
        "cmc": False,
        "card_type": False,
        "subtypes": False,
        "keywords": False,
        "oracle_text": False,
        "legend": False} #Dict of whether blank values are disallowed, eg colorless cards or no subtypes
negparams = {"set": [],
        "rarity": [],
        "color": [],
        "mana_cost": [],
        "mana_symbols": [],
        "name": [],
        "cmc": [],
        "card_type": ["Token"],
        "subtypes": [],
        "keywords": [],
        "oracle_text": [],
        "legend": []} #Values that are specifically not allowed

n = 5
selected_cards = select_cards(shortened_card_data, n, fightparams, exclusive=exclusive_params,
                              negparams=negparams, blankparams=blankparams)


for card in selected_cards:
    print(card["color"])
    print(card["subtypes"])
    print(card["card_type"])
    print(card["mana_cost"])
    print(card["name"])
    print(card["oracle_text"])
    print()

['G']
['Elf', 'Scout']
['Creature']
['1', 'G']
['Frontier Guide']
['{3}{G}, {T}: Search your library for a basic land card, put it onto the battlefield tapped, then shuffle.']

['G']
['Forest']
['Basic', 'Land']
[]
['Forest']
['({T}: Add {G}.)']

['R']
['Elemental']
['Creature']
['2', 'R']
['Molten Ravager']
['{R}: Molten Ravager gets +1/+0 until end of turn.']

['G', 'W']
[]
['Instant']
['G', '/', 'W']
['Barkshell Blessing']
['Target creature gets +2/+2 until end of turn.\nConspire (As you cast this spell, you may tap two untapped creatures you control that share a color with it. When you do, copy it and you may choose a new target for the copy.)']

['U', 'W']
[]
['Instant']
['2', 'W', '/', 'U', 'W', '/', 'U']
['Mirrorweave']
['Each other creature becomes a copy of target nonlegendary creature until end of turn.']



In [87]:

n = 50


# You'll need to execute this in multiple runs, one for each color and colorless cards, and then combine the results.
colors = ["W", "U", "B", "R", "G", []]  # Include an empty list for colorless cards
params = {"color":["R"], "set":["m10"], "cmc":[1,2,3,4,5]}
exclusive = {"name": True, "color": True, "set": True, "subtypes": True}
blankparams = {"color": True, "subtypes": False}
negparams = {"card_type": ["Land", "Token"]}

# Expected output: A deck containing an equal number of cards from each color and colorless cards, with no artifacts.
selected_cards=select_cards(shortened_card_data, 5, params, exclusive=exclusive,
                              negparams=negparams, blankparams=blankparams)

print(len(selected_cards))
for card in selected_cards:
    print(card["color"])
    print(card["mana_cost"])
    print(card["card_type"])
    print(card["subtypes"])
    print(card["keywords"])
    print(card["name"])
    print(card["cmc"])
    #print(card["rarity"])
    print(card["oracle_text"])
    print()

5
['R']
['R']
['Instant']
[]
[]
['Lightning Bolt']
[1.0]
['Lightning Bolt deals 3 damage to any target.']

['R']
['R']
['Creature']
['Goblin', 'Berserker']
['Haste']
['Raging Goblin']
[1.0]
['Haste (This creature can attack and {T} as soon as it comes under your control.)']

['R']
['2', 'R']
['Instant']
[]
[]
['Trumpet Blast']
[3.0]
['Attacking creatures get +2/+0 until end of turn.']

['R']
['1', 'R', 'R']
['Creature']
['Goblin', 'Warrior']
[]
['Goblin Artillery']
[3.0]
['{T}: Goblin Artillery deals 2 damage to any target and 3 damage to you.']

['R']
['R']
['Sorcery']
[]
[]
['Burst of Speed']
[1.0]
['Creatures you control gain haste until end of turn. (They can attack and {T} even if they just came under your control.)']



In [76]:
selected_cards[0]["set"][0]

'con'

In [80]:
from cardutil import sample_deck
a = sample_deck.pop(0)
a["set"][0]

'con'

In [79]:
a["set"][0]

'con'

In [118]:
for i in range(15):
    card = shortened_card_data[i+535]
    
    if "subtypes" in card and card["subtypes"]:
        print("here")
    for key, value in card.items():
        print(f"{key}: {value}")
    print("")

here
set: ['shm']
rarity: ['common']
color: ['R']
mana_cost: ['2', 'R']
mana_symbols: ['R']
name: ['Boggart Arsonists']
cmc: [3.0]
card_type: ['Creature']
subtypes: ['Goblin', 'Rogue']
keywords: ['Landwalk', 'Plainswalk']
oracle_text: ["Plainswalk (This creature can't be blocked as long as defending player controls a Plains.)\n{2}{R}, Sacrifice Boggart Arsonists: Destroy target Scarecrow or Plains."]
legend: [False]

set: ['shm']
rarity: ['common']
color: ['R']
mana_cost: ['3', 'R']
mana_symbols: ['R']
name: ['Burn Trail']
cmc: [4.0]
card_type: ['Sorcery']
subtypes: []
keywords: ['Conspire']
oracle_text: ['Burn Trail deals 3 damage to any target.\nConspire (As you cast this spell, you may tap two untapped creatures you control that share a color with it. When you do, copy it and you may choose a new target for the copy.)']
legend: [False]

here
set: ['shm']
rarity: ['rare']
color: ['R']
mana_cost: ['2', 'R', 'R']
mana_symbols: ['R', 'R']
name: ['Cragganwick Cremator']
cmc: [4.0]
card_t